name: Canary
on:
  schedule:
    - cron: 0 3 * * *
jobs:
  canary:
    name: Canary ${{ matrix.runtime }} ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        runtime: [deno, node]
        os: [macOS-latest, windows-latest, ubuntu-latest]
        include:
          - runtime: deno
            deno_version: canary
          - runtime: deno
            deno_version: rc
    env:
      RUST_BACKTRACE: full
      DENO_FUTURE: 1
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: ${{ matrix.deno_version }}

      - name: Setup Node
        if: ${{ matrix.runtime == 'node' }}
        uses: actions/setup-node@v4
        with:
          node-version: nightly

      - name: Setup Bun
        if: ${{ matrix.runtime == 'bun' }}
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: canary

      - name: Setup corepack
        if: ${{ matrix.runtime == 'node' }}
        run: |
          corepack enable
          corepack prepare pnpm --activate
          corepack --version
          pnpm --version

      - name: Install deps
        run: deno task setup:${{ matrix.runtime }}

      - name: Run tests
        run: deno task test:${{ matrix.runtime }}
