name: Lint

on: [push, pull_request]

jobs:

  lint:
    name: Lint source
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Setup repo
        uses: actions/checkout@v2

      - name: Setup Deno
        uses: denolib/setup-deno@v2
        with:
          deno-version: v1.x

      - name: Setup shellcheck
        run: >
          wget https://github.com/koalaman/shellcheck/releases/download/v0.7.1/shellcheck-v0.7.1.linux.x86_64.tar.xz &&
          tar -xvf shellcheck-v0.7.1.linux.x86_64.tar.xz &&
          mv shellcheck-v0.7.1/shellcheck . &&
          rm -rf shellcheck-v0.7.1 &&
          chmod +x shellcheck &&
          ./shellcheck --version

      - name: Check formatting
        run: deno fmt --check

      - name: Run linter
        run: deno lint --unstable

      - name: Run bash check
        run: ./shellcheck --shell bash <(deno run -r ./examples/command/shell-completions.ts completions bash)

      - name: Run zsh check
        run: ./shellcheck --shell bash <(deno run -r ./examples/command/shell-completions.ts completions zsh)
