name: Publish

on:
  pull_request:
  push:
    branches: [main]
  release:
    types: [published]

env:
  DENO_UNSTABLE_WORKSPACES: true
  DENO_FUTURE: 1

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Deno
        uses: denoland/setup-deno@v1

      - name: Publish (dry run)
        if: github.event_name != 'release'
        run: deno publish --dry-run

      - name: Publish
        if: github.event_name == 'release'
        run: deno publish
