name: Release
on:
  release:
    types:
      - created
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    env:
      RUST_BACKTRACE: full
    steps:
      - name: Setup repo
        uses: actions/checkout@v3

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Setup eggs
        run: deno task eggs link "${NEST_TOKEN}"
        env:
          NEST_TOKEN: ${{ secrets.NEST_TOKEN }}

      - name: Publish Nest.land
        run: deno task eggs publish --no-check --yes
