name: Test
on:
  push:
    branches: [main]
  pull_request:
jobs:
  stable:
    name: Deno Stable
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macOS-latest, windows-latest, ubuntu-latest]
        deno: [v1.x]
    env:
      RUST_BACKTRACE: full
    steps:
      - name: Setup repo
        uses: actions/checkout@v3

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: ${{ matrix.deno }}

      - name: Run tests
        run: deno task coverage

      - name: Upload coverage
        uses: codecov/codecov-action@v3
        with:
          name: ${{ matrix.os }}-${{ matrix.deno }}
          files: cov.lcov
