name: Nightly Test

on:
  schedule:
    - cron: 0 0 * * *

jobs:

  nightly:
    name: Deno Nightly
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macOS-latest, windows-latest, ubuntu-latest]
        deno_version: [ nightly ]
    steps:
      - name: Setup repo
        uses: actions/checkout@v2

      - name: Setup Deno
        uses: denolib/setup-deno@v2
        with:
          deno-version: ${{ matrix.deno_version }}

      - name: Run tests
        run: deno test --allow-all --unstable --location https://cliffy.io